# conda environment description file for Reshapr package
# testing environment
#
# Creates a conda environment in which the Reshapr package
# unit tests and coverage analysis can be run.
# Primarily intended for creation of a conda env for use in a GitHub Actions workflow.

name: reshapr-dev-test

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - bottleneck
  - click
  - dask
  - flox
  - h5netcdf
  - netCDF4
  - pip
  - python
  - pyyaml
  - rich
  - structlog
  - xarray

  # For unit tests and coverage monitoring
  - coverage
  - pytest-cov
  - pytest-randomly
  - tomli

  # For documentation links checking
  - sphinx=7.2.6
  - sphinx-notfound-page=1.0.0
  - sphinx-rtd-theme=2.0.0

  - pip:
    # install Reshapr package in editable mode
    - --editable ../
