# conda environment description file for Reshapr package user environment
#
# Create a conda environment for using of the package with:
#
#   $ conda env create -f Reshapr/envs/environment-user.yaml
#   $ conda activate reshapr

name: reshapr

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - bottleneck
  - click
  - dask
  - flox
  - h5netcdf
  - netCDF4
  - pip
  - python=3.13
  - pyyaml
  - rich
  - structlog
  - xarray

  - pip:
    # install of Reshapr package in editable mode
    - --editable ../
