# conda environment description file for readthedocs build environment

name: reshapr-dev-rtd

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.12

  # readthedocs packages
  - mock
  - pillow
  - pip
  - sphinx
  - sphinx_rtd_theme=1.2
  - sphinx-notfound-page
  - pip:
      - recommonmark
      - readthedocs-sphinx-ext
