name: sphinx-linkcheck

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: 43 14 14 * *  # 14:43 UTC on the 14th day of each month

jobs:
  sphinx-linkcheck:
    name: linkcheck docs
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      # Python version matrix is necessary because we are using the environment-test.yaml
      # environment that is also used for unit tests and coverage analysis.
      # That environment defers to the Python version(s) here so that it can be used
      # for multi-version CI.
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v2

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
           miniforge-variant: Mambaforge-pypy3
           miniforge-version: latest
           use-mamba: true
           auto-update-conda: false
           auto-activate-base: false
           channels: conda-forge,nodefaults
           channel-priority: true
           python-version: ${{ matrix.python-version }}
           environment-file: envs/environment-test.yaml
           activate-environment: reshapr-test

      - name: Install package
        shell: bash -l {0}
        run: |
          python3 -m pip install --editable $GITHUB_WORKSPACE

      - name: linkcheck docs
        shell: bash -l {0}
        run: |
          (cd docs && make linkcheck)

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Sphinx linkcheck
          fields: repo,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_SALISHSEACAST_WEBHOOK_URL }}
        if: always()
